name: Test Debug

on:
  push:
    branches:
      - 'add-message-**'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug Info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          
      - name: Extract username
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Branch: $BRANCH"
          USERNAME=$(echo "$BRANCH" | sed -E 's/add-message-([^-]+)-.*/\1/')
          echo "Username: $USERNAME"
          
      - name: Check GPG Secret
        env:
          GPG_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        run: |
          if [ -z "$GPG_KEY" ]; then
            echo "❌ GPG_PUBLIC_KEY is NOT set"
          else
            echo "✅ GPG_PUBLIC_KEY is set (length: ${#GPG_KEY})"
          fi
      
      - name: Check files
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in messages/:"
          ls -la messages/ || echo "messages/ not found"
          
      - name: Success
        run: echo "✅ All checks passed!"

